#    Copyright (C) 2024 HiTViSc Contributors
#    Contact e-mail: hitvisc@yandex.ru    
#
#    GNU GENERAL PUBLIC LICENSE
#    Version 3, 29 June 2007
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.
---
- name: Removing BOINC Server
  hosts: TargetServers

  tasks:
  # Clean the system from previous installation
  - name: Stop BOINC server processes
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./bin/stop
    args:
      chdir: "/{{ app_base_directory }}/{{ boinc_project_home }}"
      executable: /bin/bash
    ignore_errors: true

  - name: Stop apache2
    become: yes
    become_user: root
    become_method: sudo
    systemd:
      name: apache2
      state: stopped
      enabled: true

  - name: Delete BOINC server home directory
    become: yes
    become_user: root
    become_method: sudo
    file:
      path: "/{{ app_base_directory }}/{{ boinc_project_home }}"
      state: absent
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"
    ignore_errors: true

  - name: Drop project database if exists
    become: yes
    become_user: root
    become_method: sudo
    shell: echo "DROP DATABASE IF EXISTS {{ boinc_db_name }};" | mysql
    args:
      executable: /bin/bash

  - name: Delete BOINC server source code directory
    become: yes
    become_user: root
    become_method: sudo
    file:
      path: "/{{ app_base_directory }}/{{ source_root }}/boinc"
      state: absent
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"
    ignore_errors: true

  - name: Drop MySQL user
    become: yes
    become_user: root
    become_method: sudo
    shell: echo "DROP USER IF EXISTS {{ boinc_db_user }};" | mysql
    args:
      executable: /bin/bash

  - name: Remove BOINC server directories from apache2 configuration file
    become: yes
    become_user: root
    become_method: sudo
    shell: LINE_NUMBER=$(grep -n "## Settings for BOINC project" /etc/apache2/apache2.conf | awk -F ':' '{ print($1 - 1); }') ; if [ -n "$LINE_NUMBER" ] ; then cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf.bak ; head -n $LINE_NUMBER /etc/apache2/apache2.conf > /tmp/apache2.conf ; cat /tmp/apache2.conf > /etc/apache2/apache2.conf ; rm /tmp/apache2.conf ; fi
    args:
      executable: /bin/bash
