#    Copyright (C) 2024 HiTViSc Contributors
#    Contact e-mail: hitvisc@yandex.ru    
#
#    GNU GENERAL PUBLIC LICENSE
#    Version 3, 29 June 2007
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.
---
- name: Prepare the BOINC project for HiTViSc 
  hosts: TargetServers

  tasks:
  - name: Installing packages
    become: yes
    become_user: root
    become_method: sudo
    apt:
      name:
      - zip
      - unzip
      state: present

  # Deleting old version sources (if present)
  - name: Delete old directory with HiTViSc files for the BOINC project
    become: yes
    become_user: root
    become_method: sudo
    file:
      path: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc"
      state: absent

  # Copying new version sources
  - name: Copy directory with HiTViSc files for the BOINC project
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    copy:
      src: ./source/hitvisc-boinc
      dest: "/{{ app_base_directory }}/{{ source_root }}/"
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"
      mode: preserve

  # Stopping BOINC server
  - name: Stop BOINC server daemons to copy HiTViSc-related files and settings
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./bin/stop
    args:
      chdir: "/{{ app_base_directory }}/{{ boinc_project_home }}"
      executable: /bin/bash

  - name: Set execution permissions on shell scripts of HiTViSc extension of BOINC
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc" -type f -name "*.sh" -exec chmod +x {} \;
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc"

  - name: Set execution permissions on assimilator/validator scripts of HiTViSc extension of BOINC
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/bin" -type f -name "*_trivial_*" -exec chmod +x {} \;
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/bin"

  - name: Set execution permissions on AutoDock Vina wrapper of HiTViSc extension of BOINC
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps" -type f -name "*autodockvina_wrapper_x86_64-pc-linux-gnu" -exec chmod +x {} \;
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps"

  - name: Set execution permissions on AutoDock Vina of HiTViSc extension of BOINC
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps" -type f -name "*autodockvina_1.2.5_1.0_x86_64-pc-linux-gnu"
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps"

  - name: Set execution permissions on CmDock wrapper of HiTViSc extension of BOINC
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps" -type f -name "*cmdock_wrapper_1.0_x86_64-pc-linux-gnu"
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps"

  - name: Set execution permissions on CmDock of HiTViSc extension of BOINC
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps" -type f -name "*cmdock_0.2.0_1.0_x86_64-pc-linux-gnu"
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc/apps"

  #  Add HiTViSc-specific files and settings to the BOINC project
  - name: Run HiTViSc script for the BOINC project update
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./update_boinc_project.sh "/{{ app_base_directory }}/{{ boinc_project_home }}" > update_boinc_project.log 2>&1
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc"
      executable: /bin/bash

  #  Add HiTViSc-specific EXAMPLE files to the BOINC project - add EXAMPLE files for testing
  - name: Run HiTViSc script for the BOINC project update - add EXAMPLE files for testing
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./update_boinc_project_EXAMPLE.sh "/{{ app_base_directory }}/{{ boinc_project_home }}" > update_boinc_project_EXAMPLE.log 2>&1
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc"
      executable: /bin/bash

  - name: Run BOINC's script xadd to register HiTViSc applications 
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./bin/xadd
    args:
      chdir: "/{{ app_base_directory }}/{{ boinc_project_home }}"
      executable: /bin/bash

  - name: Run BOINC's script update_versions to register application versions
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: yes | ./bin/update_versions
    args:
      chdir: "/{{ app_base_directory }}/{{ boinc_project_home }}"
      executable: /bin/bash

  - name: Start BOINC server daemons to run HiTViSc-related programs
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./bin/start
    args:
      chdir: "/{{ app_base_directory }}/{{ boinc_project_home }}"
      executable: /bin/bash

  - name: Add initial BOINC user
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./add_boinc_user.sh
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/hitvisc-boinc"
      executable: /bin/bash

  - name: Create a cron entry "*/5 * * * * /app/hitboinc/bin/start --cron"
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    cron:
      name: "start BOINC project"
      minute: "*/5"
      job: "/app/hitboinc/bin/start --cron"
