#    Copyright (C) 2024 HiTViSc Contributors
#    Contact e-mail: hitvisc@yandex.ru    
#
#    GNU GENERAL PUBLIC LICENSE
#    Version 3, 29 June 2007
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.
---
- name: Rolling HiTViSc PostgreSQL RDBMS software
  hosts: TargetServers

  tasks:
  #  Finalize HiTViSc registry
  - name: Run HiTViSc registry finalize script
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./registry_finalize.sh "/{{ app_base_directory }}/{{ postgresql_base }}/{{ postgresql_environment }}" HiTViSc > registry_finalize.log
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/registry"
      executable: /bin/bash

  - name: Set execution permissions on scripts
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}" -type f -name "*.sh" -exec chmod +x {} \;
    args:
      chdir: "/{{ app_base_directory }}"

  - name: Launch front-end
    become: true
    become_user: "{{ hitvisc_user_name }}"
    shell: |
        source /home/hitviscadm/.nvm/nvm.sh
        nvm use 18
        pm2 start pm2.production.config.js
    args:
      chdir: "/{{ app_base_directory }}/hitvisc/front"
      executable: /bin/bash
