#    Copyright (C) 2024 HiTViSc Contributors
#    Contact e-mail: hitvisc@yandex.ru    
#
#    GNU GENERAL PUBLIC LICENSE
#    Version 3, 29 June 2007
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.
---
- name: Rolling HiTViSc PostgreSQL RDBMS software
  hosts: TargetServers

  tasks:
  # Clean system from previous releases
  - name: Delete directory with HiTViSc registry source code
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    file:
      path: "/{{ app_base_directory }}/{{ source_root }}/registry"
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"
      state: absent

  # Deploy HiTViSc registry
  - name: Copy directory with HiTViSc registry scripts
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    copy:
      src: ./source/registry
      dest: "/{{ app_base_directory }}/{{ source_root }}/"
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"
      mode: preserve

  - name: Set execution permissions on scripts
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/{{ source_root }}/registry/" -type f -name "*.sh" -exec chmod +x {} \;
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/registry/"

#  Create HiTViSc registry
  - name: Run HiTViSc registry create script
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./registry_build.sh "/{{ app_base_directory }}/{{ postgresql_base }}/{{ postgresql_environment }}" HiTViSc > registry_build.log
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/registry"
      executable: /bin/bash

  # Create HiTViSc example data directory
  - name: Create HiTViSc example data directory
    become: yes
    become_user: root
    become_method: sudo
    file:
      path: "/{{ app_base_directory }}/hitvisc/data"
      state: directory
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"

  # Copy HiTViSc example data
  - name: Copy HiTViSc example data
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    copy:
      src: ./source/hitvisc/data/
      dest: "/{{ app_base_directory }}/hitvisc/data/"
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"
      mode: preserve
