---
- name: Rolling HiTViSc PostgreSQL RDBMS software
  hosts: TargetServers

  tasks:
  #  Finalize HiTViSc registry
  - name: Run HiTViSc registry finalize script
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./registry_finalize.sh "/{{ app_base_directory }}/{{ postgresql_base }}/{{ postgresql_environment }}" HiTViSc > registry_finalize.log
    args:
      chdir: "/{{ app_base_directory }}/{{ source_root }}/registry"
      executable: /bin/bash

