#    Copyright (C) 2024 HiTViSc Contributors
#    Contact e-mail: hitvisc@yandex.ru    
#
#    GNU GENERAL PUBLIC LICENSE
#    Version 3, 29 June 2007
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.
---
- name: Prepare third-party bioinformatics tools
  hosts: TargetServers

  tasks:
  # Create a directory for third-party tools
  - name: Create a directory for third-party tools
    become: yes
    become_user: root
    become_method: sudo
    file:
      path: "/{{ app_base_directory }}/third-party"
      state: directory
      owner: "{{ hitvisc_user_name }}"
      group: "{{ hitvisc_group_name }}"

  - name: Set execution permissions on scripts
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    command: find "/{{ app_base_directory }}/hitvisc/bio" -type f -name "*.sh" -exec chmod +x {} \;
    args:
      chdir: "/{{ app_base_directory }}/hitvisc/bio"

  # Install Anaconda package manager to use third-party bioinformatics tools
  - name: Install Anaconda package manager to use third-party bioinformatics tools
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./install_conda.sh
    args:
      chdir: "/{{ app_base_directory }}/hitvisc/bio"
      executable: /bin/bash

  # Setup conda
  - name: Setup conda 
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./setup_conda.sh
    args:
      chdir: "/{{ app_base_directory }}/hitvisc/bio"
      executable: /bin/bash

  # Setup hitvisc-bio conda environment
  - name: Setup hitvisc-bio conda environment
    become: yes
    become_user: "{{ hitvisc_user_name }}"
    become_method: sudo
    shell: ./setup_hitvisc-bio_env.sh
    args:
      chdir: "/{{ app_base_directory }}/hitvisc/bio"
      executable: /bin/bash

