registry_database        = hitvisc
project_database         = hitboinc
project_user             = hitviscadm
project_password         = [BOINC_PROJECT_PASSWORD]
project_directory        = /app/hitboinc
boinc_results_dir        = /app/hitboinc/sample_results
boinc_user_email         = [BOINC_ADMINISTRATOR_EMAIL]
boinc_user_name          = [BOINC_ADMINISTRATOR_NAME]
boinc_user_passwd_hash   = [BOINC_ADMINISTRATOR_PASSWD_HASH]
boinc_user_authenticator = [BOINC_ADMINISTRATOR_AUTHENTICATOR]
hitvisc_api_dir          = /app/hitvisc/api
hitvisc_main_dir         = /app/hitvisc/main
hitvisc_data_dir         = /app/hitvisc/data
hitvisc_bio_dir          = /app/hitvisc/bio
hitvisc_log_dir          = /app/hitvisc/log
hitvisc_tmp_dir          = /app/hitvisc/tmp
